auth_enabled: false

server:
  http_listen_port: {{ .Values.loki.containerPorts.http }}

common:
  compactor_address: http://{{ include "grafana-loki.compactor.fullname" . }}:{{ .Values.compactor.service.ports.http }}

distributor:
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - {{ include "grafana-loki.gossip-ring.fullname" . }}

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  chunk_block_size: 262144
  chunk_encoding: snappy
  max_transfer_retries: 0
  wal:
    dir: {{ .Values.loki.dataDir }}/wal

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m

schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    shared_store: s3
    active_index_directory: {{ .Values.loki.dataDir }}/loki/index
    cache_location: {{ .Values.loki.dataDir }}/loki/cache
    cache_ttl: 168h
    index_gateway_client:
      server_address: {{ (printf "dns:///%s:9095" (include "grafana-loki.index-gateway.fullname" .)) }}
  aws:
    bucketnames: ${s3_bucket_name}
    endpoint: ${s3_endpoint}
    region: ${s3_region}
    access_key_id: ${s3_access_key}
    secret_access_key: ${s3_secret_key}
  index_queries_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      addresses: dns+{{ include "grafana-loki.memcached-index-queries.host" . }}
      service: http

chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      addresses: dns+{{ include "grafana-loki.memcached-chunks.host" . }}

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        addresses: dns+{{ include "grafana-loki.memcached-frontend.host" . }}
        max_idle_conns: 16
        timeout: 500ms
        update_interval: 1m

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://{{ include "grafana-loki.querier.fullname" . }}:{{ .Values.querier.service.ports.http }}

compactor:
  shared_store: s3

ruler:
  storage:
    type: local
    local:
      directory: {{ .Values.loki.dataDir }}/conf/rules
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  alertmanager_url: http://mimir-nginx.mimir.svc:80/alertmanager
  enable_api: true
  remote_write:
    enabled: true
    client:
      url: http://mimir-nginx.mimir.svc:80/api/v1/push
